// Generated with `curl https://getbible.net/v2/web.json | jq '[.books[].name]'`
const bookList = {
  "Genesis": 1,
  "Exodus": 2,
  "Leviticus": 3,
  "Numbers": 4,
  "Deuteronomy": 5,
  "Joshua": 6,
  "Judges": 7,
  "Ruth": 8,
  "1 Samuel": 9,
  "2 Samuel": 10,
  "1 Kings": 11,
  "2 Kings": 12,
  "1 Chronicles": 13,
  "2 Chronicles": 14,
  "Ezra": 15,
  "Nehemiah": 16,
  "Esther": 17,
  "Job": 18,
  "Psalm": 19,
  "Psalms": 19,
  "Proverbs": 20,
  "Ecclesiastes": 21,
  "Canticles": 22,
  "Song of Solomon": 22,
  "Song of Songs": 22,
  "Isaiah": 23,
  "Jeremiah": 24,
  "Lamentations": 25,
  "Ezekiel": 26,
  "Daniel": 27,
  "Hosea": 28,
  "Joel": 29,
  "Amos": 30,
  "Obadiah": 31,
  "Jonah": 32,
  "Micah": 33,
  "Nahum": 34,
  "Habakkuk": 35,
  "Zephaniah": 36,
  "Haggai": 37,
  "Zechariah": 38,
  "Malachi": 39,
  "Matthew": 40,
  "Mark": 41,
  "Luke": 42,
  "John": 43,
  "Acts": 44,
  "Romans": 45,
  "1 Corinthians": 46,
  "2 Corinthians": 47,
  "Galatians": 48,
  "Ephesians": 49,
  "Philippians": 50,
  "Colossians": 51,
  "1 Thessalonians": 52,
  "2 Thessalonians": 53,
  "1 Timothy": 54,
  "2 Timothy": 55,
  "Titus": 56,
  "Philemon": 57,
  "Hebrews": 58,
  "James": 59,
  "1 Peter": 60,
  "2 Peter": 61,
  "1 John": 62,
  "2 John": 63,
  "3 John": 64,
  "Jude": 65,
  "Revelation": 66,
}

const abbreviations = {
  '1CH': '1 Chronicles',                          
  '1CO': '1 Corinthians',
  '1JN': '1 John',
  '1KI': '1 Kings',
  '1PE': '1 Peter',
  '1SA': '1 Samuel',
  '1TH': '1 Thessalonians',
  '1TI': '1 Timothy',
  '2CH': '2 Chronicles',
  '2CO': '2 Corinthians',
  '2JN': '2 John',
  '2KI': '2 Kings',
  '2PE': '2 Peter',
  '2SA': '2 Samuel',
  '2TH': '2 Thessalonians',
  '2TI': '2 Timothy',
  '3JN': '3 John',
  'ACT': 'Acts',
  'AMO': 'Amos',
  'COL': 'Colossians',
  'DAN': 'Daniel',
  'DEU': 'Deuteronomy',
  'ECC': 'Ecclesiastes',
  'EPH': 'Ephesians',
  'EST': 'Esther',
  'EXO': 'Exodus',
  'EZK': 'Ezekiel',
  'EZR': 'Ezra',
  'GAL': 'Galatians',
  'GEN': 'Genesis',
  'HAB': 'Habakkuk',
  'HAG': 'Haggai',
  'HEB': 'Hebrews',
  'HOS': 'Hosea',
  'ISA': 'Isaiah',
  'JAS': 'James',
  'JDG': 'Judges',
  'JER': 'Jeremiah',
  'JHN': 'John',
  'JOB': 'Job',
  'JOL': 'Joel',
  'JON': 'Jonah',
  'JOS': 'Joshua',
  'JUD': 'Jude',
  'LAM': 'Lamentations',
  'LEV': 'Leviticus',
  'LUK': 'Luke',
  'MAL': 'Malachi',
  'MAT': 'Matthew',
  'MIC': 'Micah',
  'MRK': 'Mark',
  'NAM': 'Nahum',
  'NEH': 'Nehemiah',
  'NUM': 'Numbers',
  'OBA': 'Obadiah',
  'PHM': 'Philemon',
  'PHP': 'Philippians',
  'PRO': 'Proverbs',
  'PSA': 'Psalms',
  'REV': 'Revelation',
  'ROM': 'Romans',
  'RUT': 'Ruth',
  'SNG': 'Song of Solomon',
  'TIT': 'Titus',
  'ZEC': 'Zechariah',
  'ZEP': 'Zephaniah',
}

const getNumberForBookName = name => {
  const unabbreviated = abbreviations[name] || name;
  return bookList[unabbreviated];
}
module.exports = { bookList, abbreviations, getNumberForBookName };
